Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Articles" (
    "ArticleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Category" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Articles" PRIMARY KEY ("ArticleId")
);

CREATE TABLE "CancerStages" (
    "StageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "StageName" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CancerStages" PRIMARY KEY ("StageId")
);

CREATE TABLE "CancerTypes" (
    "CancerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CancerTypeName" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CancerTypes" PRIMARY KEY ("CancerId")
);

CREATE TABLE "Users" (
    "UserId" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "MobileNumber" text NULL,
    "Email" text NOT NULL,
    "AgreedTerms" boolean NOT NULL,
    "Gender" text NULL,
    "IsEmailVerified" boolean NOT NULL,
    "DeletedAt" bytea NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Patients" (
    "UserId" text NOT NULL,
    "AgeGroup" integer NOT NULL,
    "CancerTypeId" integer NOT NULL,
    "CancerStageId" integer NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Patients_CancerStages_CancerStageId" FOREIGN KEY ("CancerStageId") REFERENCES "CancerStages" ("StageId") ON DELETE CASCADE,
    CONSTRAINT "FK_Patients_CancerTypes_CancerTypeId" FOREIGN KEY ("CancerTypeId") REFERENCES "CancerTypes" ("CancerId") ON DELETE CASCADE,
    CONSTRAINT "FK_Patients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Interests" (
    "InterestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "LogoURL" text NOT NULL,
    "PatientUserId" text NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Interests" PRIMARY KEY ("InterestId"),
    CONSTRAINT "FK_Interests_Patients_PatientUserId" FOREIGN KEY ("PatientUserId") REFERENCES "Patients" ("UserId")
);

CREATE TABLE "Questions" (
    "QuestionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Category" text NOT NULL,
    "Description" text NOT NULL,
    "PatientUserId" text NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("QuestionId"),
    CONSTRAINT "FK_Questions_Patients_PatientUserId" FOREIGN KEY ("PatientUserId") REFERENCES "Patients" ("UserId"),
    CONSTRAINT "FK_Questions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "InterestUser" (
    "InterestsInterestId" integer NOT NULL,
    "UsersUserId" text NOT NULL,
    CONSTRAINT "PK_InterestUser" PRIMARY KEY ("InterestsInterestId", "UsersUserId"),
    CONSTRAINT "FK_InterestUser_Interests_InterestsInterestId" FOREIGN KEY ("InterestsInterestId") REFERENCES "Interests" ("InterestId") ON DELETE CASCADE,
    CONSTRAINT "FK_InterestUser_Users_UsersUserId" FOREIGN KEY ("UsersUserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Answers" (
    "AnswerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" text NOT NULL,
    "QuestionId" integer NOT NULL,
    "Content" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Answers" PRIMARY KEY ("AnswerId"),
    CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("QuestionId") ON DELETE CASCADE
);

CREATE TABLE "Bookmarks" (
    "BookmarkId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ArticleId" integer NULL,
    "Type" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bookmarks" PRIMARY KEY ("BookmarkId"),
    CONSTRAINT "FK_Bookmarks_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("ArticleId"),
    CONSTRAINT "FK_Bookmarks_Patients_UserId" FOREIGN KEY ("UserId") REFERENCES "Patients" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Doctors" (
    "UserId" text NOT NULL,
    "University" text NOT NULL,
    "Degree" text NOT NULL,
    "MedicalField" text NOT NULL,
    "VerificationStatusId" integer NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Doctors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "VerificationStatus" (
    "VerificationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TargetDoctorUserId" text NOT NULL,
    "VerifierUserId" text NOT NULL,
    "RowVersion" bytea NOT NULL,
    "Notes" text NOT NULL,
    CONSTRAINT "PK_VerificationStatus" PRIMARY KEY ("VerificationId"),
    CONSTRAINT "FK_VerificationStatus_Doctors_TargetDoctorUserId" FOREIGN KEY ("TargetDoctorUserId") REFERENCES "Doctors" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_VerificationStatus_Users_VerifierUserId" FOREIGN KEY ("VerifierUserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Answers_DoctorId" ON "Answers" ("DoctorId");

CREATE INDEX "IX_Answers_QuestionId" ON "Answers" ("QuestionId");

CREATE INDEX "IX_Bookmarks_ArticleId" ON "Bookmarks" ("ArticleId");

CREATE INDEX "IX_Bookmarks_UserId" ON "Bookmarks" ("UserId");

CREATE INDEX "IX_Doctors_VerificationStatusId" ON "Doctors" ("VerificationStatusId");

CREATE INDEX "IX_Interests_PatientUserId" ON "Interests" ("PatientUserId");

CREATE INDEX "IX_InterestUser_UsersUserId" ON "InterestUser" ("UsersUserId");

CREATE INDEX "IX_Patients_CancerStageId" ON "Patients" ("CancerStageId");

CREATE INDEX "IX_Patients_CancerTypeId" ON "Patients" ("CancerTypeId");

CREATE INDEX "IX_Questions_PatientUserId" ON "Questions" ("PatientUserId");

CREATE INDEX "IX_Questions_UserId" ON "Questions" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_MobileNumber" ON "Users" ("MobileNumber");

CREATE INDEX "IX_VerificationStatus_TargetDoctorUserId" ON "VerificationStatus" ("TargetDoctorUserId");

CREATE INDEX "IX_VerificationStatus_VerifierUserId" ON "VerificationStatus" ("VerifierUserId");

ALTER TABLE "Answers" ADD CONSTRAINT "FK_Answers_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("UserId") ON DELETE CASCADE;

ALTER TABLE "Bookmarks" ADD CONSTRAINT "FK_Bookmarks_Doctors_UserId" FOREIGN KEY ("UserId") REFERENCES "Doctors" ("UserId") ON DELETE CASCADE;

ALTER TABLE "Doctors" ADD CONSTRAINT "FK_Doctors_VerificationStatus_VerificationStatusId" FOREIGN KEY ("VerificationStatusId") REFERENCES "VerificationStatus" ("VerificationId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231001155547_make-UserId-string', '7.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231001174541_optional-verification-status', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Doctors" DROP CONSTRAINT "FK_Doctors_VerificationStatus_VerificationStatusId";

ALTER TABLE "Doctors" ALTER COLUMN "VerificationStatusId" DROP NOT NULL;

ALTER TABLE "Doctors" ADD CONSTRAINT "FK_Doctors_VerificationStatus_VerificationStatusId" FOREIGN KEY ("VerificationStatusId") REFERENCES "VerificationStatus" ("VerificationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231001183129_Optional-VerificationStatus-Id', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Interests" DROP CONSTRAINT "FK_Interests_Patients_PatientUserId";

DROP INDEX "IX_Interests_PatientUserId";

ALTER TABLE "Interests" DROP COLUMN "PatientUserId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231002211535_rm-interests-patients', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Interests" ADD "TargetUserType" integer NOT NULL DEFAULT 0;

CREATE TABLE "ResourceLocalization" (
    "TranslationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Language" text NOT NULL,
    "Translation" jsonb NOT NULL,
    "CancerStageStageId" integer NULL,
    "CancerTypeCancerId" integer NULL,
    "InterestId" integer NULL,
    CONSTRAINT "PK_ResourceLocalization" PRIMARY KEY ("TranslationId"),
    CONSTRAINT "FK_ResourceLocalization_CancerStages_CancerStageStageId" FOREIGN KEY ("CancerStageStageId") REFERENCES "CancerStages" ("StageId"),
    CONSTRAINT "FK_ResourceLocalization_CancerTypes_CancerTypeCancerId" FOREIGN KEY ("CancerTypeCancerId") REFERENCES "CancerTypes" ("CancerId"),
    CONSTRAINT "FK_ResourceLocalization_Interests_InterestId" FOREIGN KEY ("InterestId") REFERENCES "Interests" ("InterestId")
);

CREATE INDEX "IX_ResourceLocalization_CancerStageStageId" ON "ResourceLocalization" ("CancerStageStageId");

CREATE INDEX "IX_ResourceLocalization_CancerTypeCancerId" ON "ResourceLocalization" ("CancerTypeCancerId");

CREATE INDEX "IX_ResourceLocalization_InterestId" ON "ResourceLocalization" ("InterestId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231009215401_translations-interests', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "CancerTypes" ADD "LogoURL" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231012143125_test-model-change', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "CancerStages" ADD "LogoURL" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231015043744_add-logourl-cancerstage', '7.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Photos" (
    "PhotoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhotoURL" text NOT NULL,
    "Usage" integer NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Photos" PRIMARY KEY ("PhotoId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231017031908_welcome-photos', '7.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Countries" (
    "CountryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "AlphaCode" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("CountryId")
);

CREATE TABLE "CountryStates" (
    "CountryStateId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CountryId" integer NOT NULL,
    "StateCode" text NOT NULL,
    "Latitude" text NOT NULL,
    "Longitude" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CountryStates" PRIMARY KEY ("CountryStateId"),
    CONSTRAINT "FK_CountryStates_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("CountryId") ON DELETE CASCADE
);

CREATE INDEX "IX_CountryStates_CountryId" ON "CountryStates" ("CountryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231023184403_add-university', '7.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Universities" (
    "UniversityId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CountryName" text NOT NULL,
    "CountryCode" text NOT NULL,
    "StateCode" text NOT NULL,
    "StateName" text NOT NULL,
    "UniversityName" text NOT NULL,
    "Id" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Universities" PRIMARY KEY ("UniversityId")
);

CREATE INDEX "IX_Universities_CountryCode" ON "Universities" ("CountryCode");

CREATE INDEX "IX_Universities_CountryCode_StateCode" ON "Universities" ("CountryCode", "StateCode");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231109041156_add-university-model', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Doctors" ADD "CertificationPath" text NOT NULL DEFAULT '';

ALTER TABLE "Doctors" ADD "NationalIDPath" text NOT NULL DEFAULT '';

CREATE TABLE "Contents" (
    "ContentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ParentContentId" integer NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    "Raw" jsonb NOT NULL,
    "AuthorUserId" text NOT NULL,
    "AssignedTo" integer NULL,
    "Phase" integer NOT NULL,
    "Tags" text[] NOT NULL,
    "Visibility" integer NOT NULL,
    "Attachments" text[] NOT NULL,
    CONSTRAINT "PK_Contents" PRIMARY KEY ("ContentId"),
    CONSTRAINT "FK_Contents_Contents_ParentContentId" FOREIGN KEY ("ParentContentId") REFERENCES "Contents" ("ContentId"),
    CONSTRAINT "FK_Contents_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Contents_AssignedTo" ON "Contents" ("AssignedTo");

CREATE INDEX "IX_Contents_AuthorUserId" ON "Contents" ("AuthorUserId");

CREATE INDEX "IX_Contents_ParentContentId" ON "Contents" ("ParentContentId");

CREATE INDEX "IX_Contents_Tags" ON "Contents" ("Tags");

CREATE INDEX "IX_Contents_Type" ON "Contents" ("Type");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231117065846_questions', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" DROP COLUMN "DeletedAt";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231118161837_deletedAt', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" DROP COLUMN "Id";

ALTER TABLE "Universities" DROP COLUMN "Id";

ALTER TABLE "Universities" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Questions" DROP COLUMN "Id";

ALTER TABLE "Questions" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Photos" DROP COLUMN "Id";

ALTER TABLE "Photos" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Patients" DROP COLUMN "Id";

ALTER TABLE "Interests" DROP COLUMN "Id";

ALTER TABLE "Interests" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Doctors" DROP COLUMN "CertificationPath";

ALTER TABLE "Doctors" DROP COLUMN "Id";

ALTER TABLE "Doctors" DROP COLUMN "NationalIDPath";

ALTER TABLE "CountryStates" DROP COLUMN "Id";

ALTER TABLE "CountryStates" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Countries" DROP COLUMN "Id";

ALTER TABLE "Countries" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Contents" DROP COLUMN "CreatedAt";

ALTER TABLE "CancerTypes" DROP COLUMN "Id";

ALTER TABLE "CancerTypes" DROP COLUMN "LastModifiedDate";

ALTER TABLE "CancerStages" DROP COLUMN "Id";

ALTER TABLE "CancerStages" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Bookmarks" DROP COLUMN "Id";

ALTER TABLE "Bookmarks" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Articles" DROP COLUMN "Id";

ALTER TABLE "Articles" DROP COLUMN "LastModifiedDate";

ALTER TABLE "Answers" DROP COLUMN "Id";

ALTER TABLE "Answers" DROP COLUMN "LastModifiedDate";

ALTER TABLE "VerificationStatus" ADD "Active" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "VerificationStatus" ADD "CreatedDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "VerificationStatus" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "VerificationStatus" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Users" ADD "CreatedDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Users" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Users" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Universities" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Universities" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Questions" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Questions" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Photos" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Photos" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Patients" ADD "CreatedDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Patients" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Patients" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Interests" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Interests" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Doctors" ADD "CreatedDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Doctors" ADD "CredentialsAttachments" text[] NOT NULL DEFAULT ARRAY[]::text[];

ALTER TABLE "Doctors" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Doctors" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "CountryStates" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "CountryStates" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Countries" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Countries" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Contents" ADD "Active" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Contents" ADD "CreatedDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "CancerTypes" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "CancerTypes" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "CancerStages" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "CancerStages" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Bookmarks" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Bookmarks" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Articles" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Articles" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Answers" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Answers" ADD "UpdatedAt" timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231118162100_delete-users-deleted-at-2', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Doctors" DROP CONSTRAINT "FK_Doctors_VerificationStatus_VerificationStatusId";

DROP TABLE "VerificationStatus";

DROP INDEX "IX_Doctors_VerificationStatusId";

ALTER TABLE "Interests" DROP COLUMN "TargetUserType";

ALTER TABLE "Doctors" DROP COLUMN "VerificationStatusId";

CREATE TYPE user_type AS ENUM ('patient', 'doctor');
CREATE TYPE verification_status AS ENUM ('pending', 'approved', 'more_info_needed', 'rejected');

ALTER TABLE "Doctors" ADD "VerificationStatus" verification_status NOT NULL DEFAULT 'pending'::verification_status;

CREATE TABLE "VerificationStatusEvent" (
    "TargetDoctorUserId" text NOT NULL,
    "VerifierUserId" text NOT NULL,
    "Notes" text NOT NULL,
    "UserId" text NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_VerificationStatusEvent" PRIMARY KEY ("TargetDoctorUserId"),
    CONSTRAINT "FK_VerificationStatusEvent_Doctors_TargetDoctorUserId" FOREIGN KEY ("TargetDoctorUserId") REFERENCES "Doctors" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_VerificationStatusEvent_Doctors_UserId" FOREIGN KEY ("UserId") REFERENCES "Doctors" ("UserId"),
    CONSTRAINT "FK_VerificationStatusEvent_Users_VerifierUserId" FOREIGN KEY ("VerifierUserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_VerificationStatusEvent_UserId" ON "VerificationStatusEvent" ("UserId");

CREATE INDEX "IX_VerificationStatusEvent_VerifierUserId" ON "VerificationStatusEvent" ("VerifierUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231120004545_remove-target-user-type', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Interests" ADD "TargetUserType" user_type NOT NULL DEFAULT 'patient'::user_type;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231120004718_verification-status', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "VerificationStatusEvent" DROP CONSTRAINT "PK_VerificationStatusEvent";

ALTER TABLE "VerificationStatusEvent" ADD "EventId" integer GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "VerificationStatusEvent" ADD CONSTRAINT "PK_VerificationStatusEvent" PRIMARY KEY ("EventId");

CREATE INDEX "IX_VerificationStatusEvent_TargetDoctorUserId" ON "VerificationStatusEvent" ("TargetDoctorUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231120023322_auto-generated-id-events-table', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "VerificationStatusEvent" ADD "Status" verification_status NOT NULL DEFAULT 'pending'::verification_status;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231120025658_verification-status-field', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TYPE verification_status ADD VALUE 'more_info_needed' BEFORE 'approved';
ALTER TYPE verification_status ADD VALUE 'rejected' BEFORE 'more_info_needed';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231120204839_reorder-verificationstatus', '7.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231203162515_fix-resources', '7.0.11');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Contents_Tags";

ALTER TABLE "Contents" DROP COLUMN "Attachments";

ALTER TABLE "Contents" DROP COLUMN "Tags";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231217030745_remove-tags-attachments', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Contents" ADD "Attachments" jsonb NOT NULL;

ALTER TABLE "Contents" ADD "Tags" jsonb NOT NULL;

CREATE INDEX "IX_Contents_Tags" ON "Contents" ("Tags");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231217030811_add-tags-attachments', '7.0.11');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Contents_Type";

ALTER TABLE "Contents" DROP COLUMN "Phase";

ALTER TABLE "Contents" DROP COLUMN "Type";

ALTER TABLE "Contents" DROP COLUMN "Visibility";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231218015327_remove-enum-from-contents', '7.0.11');

COMMIT;

START TRANSACTION;

CREATE TYPE content_type AS ENUM ('category', 'question', 'answer', 'blood_donation');
CREATE TYPE phase AS ENUM ('draft', 'published');
CREATE TYPE visibility AS ENUM ('public', 'private');

ALTER TABLE "Contents" ADD "Phase" phase NOT NULL DEFAULT 'draft'::phase;

ALTER TABLE "Contents" ADD "Type" content_type NOT NULL DEFAULT 'category'::content_type;

ALTER TABLE "Contents" ADD "Visibility" visibility NOT NULL DEFAULT 'public'::visibility;

CREATE INDEX "IX_Contents_Type" ON "Contents" ("Type");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231218020032_fix-migrations', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ResourceLocalization" DROP CONSTRAINT "FK_ResourceLocalization_CancerStages_CancerStageStageId";

ALTER TABLE "ResourceLocalization" DROP CONSTRAINT "FK_ResourceLocalization_CancerTypes_CancerTypeCancerId";

ALTER TABLE "ResourceLocalization" DROP CONSTRAINT "FK_ResourceLocalization_Interests_InterestId";

ALTER TABLE "ResourceLocalization" DROP CONSTRAINT "PK_ResourceLocalization";

DROP INDEX "IX_ResourceLocalization_CancerStageStageId";

DROP INDEX "IX_ResourceLocalization_CancerTypeCancerId";

DROP INDEX "IX_ResourceLocalization_InterestId";

ALTER TABLE "ResourceLocalization" DROP COLUMN "CancerStageStageId";

ALTER TABLE "ResourceLocalization" DROP COLUMN "CancerTypeCancerId";

ALTER TABLE "ResourceLocalization" DROP COLUMN "InterestId";

ALTER TABLE "ResourceLocalization" RENAME TO "ResourceLocalizations";

ALTER TABLE "Interests" ADD "TranslationId" integer NULL;

ALTER TABLE "CancerTypes" ADD "TranslationId" integer NULL;

ALTER TABLE "CancerStages" ADD "TranslationId" integer NULL;

ALTER TABLE "ResourceLocalizations" ALTER COLUMN "TranslationId" DROP IDENTITY;

ALTER TABLE "ResourceLocalizations" ADD CONSTRAINT "PK_ResourceLocalizations" PRIMARY KEY ("TranslationId", "Language");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240101054052_refactor-translations', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Contents" ADD "TranslationId" integer NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240101061450_content-translation', '7.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240105054026_articles-views-flatten-search', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Bookmarks" DROP CONSTRAINT "FK_Bookmarks_Articles_ArticleId";

ALTER TABLE "Bookmarks" DROP CONSTRAINT "FK_Bookmarks_Doctors_UserId";

ALTER TABLE "Bookmarks" DROP CONSTRAINT "FK_Bookmarks_Patients_UserId";

ALTER TABLE "Questions" DROP CONSTRAINT "FK_Questions_Patients_PatientUserId";

DROP TABLE "Articles";

DROP INDEX "IX_Questions_PatientUserId";

DROP INDEX "IX_Bookmarks_ArticleId";

ALTER TABLE "Questions" DROP COLUMN "PatientUserId";

ALTER TABLE "Bookmarks" DROP COLUMN "ArticleId";

ALTER TABLE "Bookmarks" DROP COLUMN "Type";

ALTER TABLE "Bookmarks" ADD "ContentId" integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX "IX_Bookmarks_ContentId" ON "Bookmarks" ("ContentId");

CREATE INDEX "IX_Bookmarks_UserId_ContentId" ON "Bookmarks" ("UserId", "ContentId");

ALTER TABLE "Bookmarks" ADD CONSTRAINT "FK_Bookmarks_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("ContentId") ON DELETE CASCADE;

ALTER TABLE "Bookmarks" ADD CONSTRAINT "FK_Bookmarks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240106160611_bookmarking-api', '7.0.11');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Bookmarks_ContentId";

DROP INDEX "IX_Bookmarks_UserId_ContentId";

CREATE INDEX "IX_Bookmarks_ContentId" ON "Bookmarks" ("ContentId");

CREATE UNIQUE INDEX "IX_Bookmarks_UserId_ContentId" ON "Bookmarks" ("UserId", "ContentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240106170419_bookmark-api', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Bookmarks" ADD CONSTRAINT "AK_Bookmarks_UserId_ContentId" UNIQUE ("UserId", "ContentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240106173825_bookmark-constraint', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Interests" ADD "StyleBackgroundColorHex" text NOT NULL DEFAULT '';

ALTER TABLE "Interests" ADD "StyleForegroundColorHex" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240113163441_article-interest', '7.0.11');

COMMIT;

START TRANSACTION;

CREATE OR REPLACE PROCEDURE insert_content(parent_content_id INTEGER, author_user_id text, raw jsonb, OUT rows_inserted INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
    generated_id INTEGER; rows_inserted INTEGER; 
BEGIN
INSERT INTO public."ResourceLocalizations" ("TranslationId", "Language", "Translation") VALUES ((floor(random() * (100000000 - 1 + 1)) + 1), 'en', raw::jsonb) RETURNING "TranslationId" INTO generated_id; INSERT INTO public."Contents" ( "ParentContentId", "AuthorUserId", "Raw", "Active", "CreatedDate", "Phase", "TranslationId", "Attachments", "Tags" ) VALUES ( parent_content_id, author_user_id, raw::jsonb, TRUE, NOW(), 'published', generated_id, '[]'::jsonb, '[]'::jsonb ); GET DIAGNOSTICS rows_inserted = ROW_COUNT; 
END;
$$;


CREATE OR REPLACE VIEW public."FlattenedResourceLocalizations" AS SELECT t."TranslationId", t."Language", jsonb_each.key, (jsonb_each.value)::text AS value FROM ("ResourceLocalizations" t CROSS JOIN LATERAL jsonb_each(t."Translation") jsonb_each(key, value));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240113234928_create-contenttype-sp', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Contents" ADD "InterestIDs" integer[] NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240115161342_interests-content', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Contents" DROP COLUMN "InterestIDs";

CREATE TABLE "ContentInterest" (
    "ContentsContentId" integer NOT NULL,
    "InterestsInterestId" integer NOT NULL,
    CONSTRAINT "PK_ContentInterest" PRIMARY KEY ("ContentsContentId", "InterestsInterestId"),
    CONSTRAINT "FK_ContentInterest_Contents_ContentsContentId" FOREIGN KEY ("ContentsContentId") REFERENCES "Contents" ("ContentId") ON DELETE CASCADE,
    CONSTRAINT "FK_ContentInterest_Interests_InterestsInterestId" FOREIGN KEY ("InterestsInterestId") REFERENCES "Interests" ("InterestId") ON DELETE CASCADE
);

CREATE INDEX "IX_ContentInterest_InterestsInterestId" ON "ContentInterest" ("InterestsInterestId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240115175819_content-interest-many-to-many', '7.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Medications" (
    "MedicationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "MedicationType" text NOT NULL,
    "MedicationName" text NOT NULL,
    "Photo" text NULL,
    "Dosage" integer NOT NULL,
    "Duration" integer NOT NULL,
    "Frequency" text NOT NULL,
    "StartDate" text NOT NULL,
    "EndDate" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Medications" PRIMARY KEY ("MedicationId"),
    CONSTRAINT "FK_Medications_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Medications_PatientId" ON "Medications" ("PatientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240117025734_Add-medication-tracker-table', '7.0.11');

COMMIT;

START TRANSACTION;

DROP TABLE "Medications";

CREATE TYPE day_of_the_week AS ENUM ('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday');
CREATE TYPE frequency_interval AS ENUM ('every_day', 'every8hours', 'every12hours', 'every_other_day');
CREATE TYPE medication_type AS ENUM ('tablet', 'liquid_filled_capsule', 'capsule', 'cream', 'device', 'drops', 'foam', 'gel', 'inhaler', 'injection', 'liquid', 'lotion', 'ointment', 'patch', 'powder', 'spray', 'suppository', 'topical');
CREATE TYPE medication_unit AS ENUM ('mg', 'mcg', 'g', 'ml', 'percentage');
CREATE TYPE schedule_entity_type AS ENUM ('medication', 'routine_test', 'appointment');
CREATE TYPE schedule_frequency AS ENUM ('regular_intervals', 'specific_days', 'as_needed');

CREATE TABLE "Schedules" (
    "ScheduleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CronExpression" text NOT NULL,
    "UserId" text NOT NULL,
    "EntityType" integer NOT NULL,
    "Entity" jsonb NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Schedules" PRIMARY KEY ("ScheduleId"),
    CONSTRAINT "FK_Schedules_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "SymptomLookups" (
    "SymptomLookupId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_SymptomLookups" PRIMARY KEY ("SymptomLookupId")
);

CREATE TABLE "ScheduleInstances" (
    "ScheduleInstanceId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScheduleId" integer NOT NULL,
    "Time" timestamp with time zone NULL,
    "Done" boolean NULL,
    "Skipped" boolean NULL,
    "Missed" boolean NULL,
    "Notes" text NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ScheduleInstances" PRIMARY KEY ("ScheduleInstanceId"),
    CONSTRAINT "FK_ScheduleInstances_Schedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "Schedules" ("ScheduleId") ON DELETE CASCADE
);

CREATE TABLE "Symptoms" (
    "SymptomId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SymptomLookupId" integer NOT NULL,
    "PatientUserId" text NOT NULL,
    "Time" timestamp with time zone NULL,
    "Details" text NOT NULL,
    "PhotoLink" text NULL,
    "Notes" text NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Symptoms" PRIMARY KEY ("SymptomId"),
    CONSTRAINT "FK_Symptoms_Patients_PatientUserId" FOREIGN KEY ("PatientUserId") REFERENCES "Patients" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_Symptoms_SymptomLookups_SymptomLookupId" FOREIGN KEY ("SymptomLookupId") REFERENCES "SymptomLookups" ("SymptomLookupId") ON DELETE CASCADE
);

CREATE TABLE "ScheduleSymptom" (
    "SchedulesScheduleId" integer NOT NULL,
    "SymptomId" integer NOT NULL,
    CONSTRAINT "PK_ScheduleSymptom" PRIMARY KEY ("SchedulesScheduleId", "SymptomId"),
    CONSTRAINT "FK_ScheduleSymptom_Schedules_SchedulesScheduleId" FOREIGN KEY ("SchedulesScheduleId") REFERENCES "Schedules" ("ScheduleId") ON DELETE CASCADE,
    CONSTRAINT "FK_ScheduleSymptom_Symptoms_SymptomId" FOREIGN KEY ("SymptomId") REFERENCES "Symptoms" ("SymptomId") ON DELETE CASCADE
);

CREATE INDEX "IX_ScheduleInstances_ScheduleId" ON "ScheduleInstances" ("ScheduleId");

CREATE INDEX "IX_Schedules_EntityType_UserId" ON "Schedules" ("EntityType", "UserId");

CREATE INDEX "IX_Schedules_UserId" ON "Schedules" ("UserId");

CREATE INDEX "IX_ScheduleSymptom_SymptomId" ON "ScheduleSymptom" ("SymptomId");

CREATE INDEX "IX_Symptoms_PatientUserId" ON "Symptoms" ("PatientUserId");

CREATE INDEX "IX_Symptoms_SymptomLookupId" ON "Symptoms" ("SymptomLookupId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240128184040_reminders', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SymptomLookups" ADD "TranslationId" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240129145834_symptom-lookup', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SymptomLookups" DROP COLUMN "TranslationId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240129160354_fix-translation-id-type-1', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SymptomLookups" ADD "TranslationId" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240129160409_fix-translation-id-type', '7.0.11');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Schedules_EntityType_UserId";

ALTER TABLE "Schedules" DROP COLUMN "EntityType";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240130051249_fix-enum-types-1', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Schedules" ADD "EntityType" schedule_entity_type NOT NULL DEFAULT 'medication'::schedule_entity_type;

CREATE INDEX "IX_Schedules_EntityType_UserId" ON "Schedules" ("EntityType", "UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240130051301_fix-enum-types', '7.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240131225218_triggers', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Schedules" ADD "StartDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240207044743_start-date', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Schedules" ADD CONSTRAINT "CronExpression" CHECK ("CronExpression" ~* '/(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5})/');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240210160652_cron-delete-bad-migration', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Schedules" DROP CONSTRAINT "CronExpression";

ALTER TABLE "Schedules" ADD CONSTRAINT "CronExpression" CHECK ("CronExpression" ~* '^(\*|[0-9]{1,2})(\/[0-9]{1,2})?\s+(\*|[0-9]{1,2})(\/[0-9]{1,2})?\s+(\*|[0-9]{1,2})(\/[0-9]{1,2})?\s+(\*|[0-9]{1,2})(\/[0-9]{1,2})?\s+(\*|[0-9]{1,2})(\/[0-9]{1,2})?$');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240210161703_cron-update-regex', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Schedules" DROP CONSTRAINT "CronExpression";

ALTER TABLE "Schedules" ADD CONSTRAINT "CronExpression" CHECK ("CronExpression" ~* '^((\*|[0-5]?[0-9])(\/[0-5]?[0-9])?\s*){4}((\*|[0-5]?[0-9])|,)+$');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240211190457_cron-fix-regex-2', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Symptoms" ADD "SymptomLookupIds" integer[] NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240226053602_multiple-symptomids', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Schedules" ALTER COLUMN "CronExpression" SET DEFAULT '0 0 1 */12 *';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240308141730_cron-expression-default', '7.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240308142655_one-off-schedule', '7.0.11');

COMMIT;


