using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace YaqeenDAL.Migrations
{
    /// <inheritdoc />
    public partial class autogeneratedideventstable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_VerificationStatusEvent",
                table: "VerificationStatusEvent");

            migrationBuilder.AddColumn<int>(
                name: "EventId",
                table: "VerificationStatusEvent",
                type: "integer",
                nullable: false,
                defaultValue: 0)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AddPrimaryKey(
                name: "PK_VerificationStatusEvent",
                table: "VerificationStatusEvent",
                column: "EventId");

            migrationBuilder.CreateIndex(
                name: "IX_VerificationStatusEvent_TargetDoctorUserId",
                table: "VerificationStatusEvent",
                column: "TargetDoctorUserId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_VerificationStatusEvent",
                table: "VerificationStatusEvent");

            migrationBuilder.DropIndex(
                name: "IX_VerificationStatusEvent_TargetDoctorUserId",
                table: "VerificationStatusEvent");

            migrationBuilder.DropColumn(
                name: "EventId",
                table: "VerificationStatusEvent");

            migrationBuilder.AddPrimaryKey(
                name: "PK_VerificationStatusEvent",
                table: "VerificationStatusEvent",
                column: "TargetDoctorUserId");
        }
    }
}
