SET check_function_bodies = false;
CREATE TYPE public.user_type AS ENUM (
    'patient',
    'doctor'
);
CREATE TYPE public.verification_status AS ENUM (
    'pending',
    'more_info_needed',
    'approved',
    'rejected'
);
CREATE TABLE public."Answers" (
    "AnswerId" integer NOT NULL,
    "DoctorId" text NOT NULL,
    "QuestionId" integer NOT NULL,
    "Content" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Answers" ALTER COLUMN "AnswerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Answers_AnswerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Articles" (
    "ArticleId" integer NOT NULL,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Category" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Articles" ALTER COLUMN "ArticleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Articles_ArticleId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Bookmarks" (
    "BookmarkId" integer NOT NULL,
    "UserId" text NOT NULL,
    "ArticleId" integer,
    "Type" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Bookmarks" ALTER COLUMN "BookmarkId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Bookmarks_BookmarkId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."CancerStages" (
    "StageId" integer NOT NULL,
    "StageName" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LogoURL" text,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."CancerStages" ALTER COLUMN "StageId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CancerStages_StageId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."CancerTypes" (
    "CancerId" integer NOT NULL,
    "CancerTypeName" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
    "LogoURL" text DEFAULT ''::text NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."CancerTypes" ALTER COLUMN "CancerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CancerTypes_CancerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Contents" (
    "ContentId" integer NOT NULL,
    "ParentContentId" integer,
    "Type" integer NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "Raw" jsonb NOT NULL,
    "AuthorUserId" text NOT NULL,
    "AssignedTo" integer,
    "Phase" integer NOT NULL,
    "Tags" text[] NOT NULL,
    "Visibility" integer NOT NULL,
    "Attachments" text[] NOT NULL,
    "Active" boolean DEFAULT false NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);
ALTER TABLE public."Contents" ALTER COLUMN "ContentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contents_ContentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Countries" (
    "CountryId" integer NOT NULL,
    "Name" text NOT NULL,
    "AlphaCode" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Countries" ALTER COLUMN "CountryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Countries_CountryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."CountryStates" (
    "CountryStateId" integer NOT NULL,
    "Name" text NOT NULL,
    "CountryId" integer NOT NULL,
    "StateCode" text NOT NULL,
    "Latitude" text NOT NULL,
    "Longitude" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."CountryStates" ALTER COLUMN "CountryStateId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CountryStates_CountryStateId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Doctors" (
    "UserId" text NOT NULL,
    "University" text NOT NULL,
    "Degree" text NOT NULL,
    "MedicalField" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "CredentialsAttachments" text[] DEFAULT ARRAY[]::text[] NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "VerificationStatus" public.verification_status DEFAULT 'pending'::public.verification_status NOT NULL
);
CREATE TABLE public."InterestDoctor" (
    "InterestId" integer NOT NULL,
    "DoctorId" text NOT NULL
);
COMMENT ON TABLE public."InterestDoctor" IS 'this table contain doctor intersts';
CREATE TABLE public."InterestUser" (
    "InterestsInterestId" integer NOT NULL,
    "UsersUserId" text NOT NULL
);
CREATE TABLE public."Interests" (
    "InterestId" integer NOT NULL,
    "Name" text NOT NULL,
    "LogoURL" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "TargetUserType" public.user_type DEFAULT 'patient'::public.user_type NOT NULL
);
ALTER TABLE public."Interests" ALTER COLUMN "InterestId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Interests_InterestId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."IntersPatient" (
    "InterestId" integer NOT NULL,
    "PatientId" text NOT NULL
);
COMMENT ON TABLE public."IntersPatient" IS 'This table return patient interests';
CREATE TABLE public."Patients" (
    "UserId" text NOT NULL,
    "AgeGroup" integer NOT NULL,
    "CancerTypeId" integer NOT NULL,
    "CancerStageId" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
CREATE TABLE public."Photos" (
    "PhotoId" integer NOT NULL,
    "PhotoURL" text NOT NULL,
    "Usage" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Photos" ALTER COLUMN "PhotoId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Photos_PhotoId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Questions" (
    "QuestionId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Category" text NOT NULL,
    "Description" text NOT NULL,
    "PatientUserId" text,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Questions" ALTER COLUMN "QuestionId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Questions_QuestionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."ResourceLocalization" (
    "TranslationId" integer NOT NULL,
    "Language" text NOT NULL,
    "Translation" jsonb NOT NULL,
    "CancerStageStageId" integer,
    "CancerTypeCancerId" integer,
    "InterestId" integer
);
ALTER TABLE public."ResourceLocalization" ALTER COLUMN "TranslationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ResourceLocalization_TranslationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Universities" (
    "UniversityId" integer NOT NULL,
    "CountryName" text NOT NULL,
    "CountryCode" text NOT NULL,
    "StateCode" text NOT NULL,
    "StateName" text NOT NULL,
    "UniversityName" text NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
ALTER TABLE public."Universities" ALTER COLUMN "UniversityId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Universities_UniversityId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."Users" (
    "UserId" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "MobileNumber" text,
    "Email" text NOT NULL,
    "AgreedTerms" boolean NOT NULL,
    "Gender" text,
    "IsEmailVerified" boolean NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone
);
CREATE TABLE public."VerificationStatusEvent" (
    "TargetDoctorUserId" text NOT NULL,
    "VerifierUserId" text NOT NULL,
    "Notes" text NOT NULL,
    "UserId" text,
    "Active" boolean NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "EventId" integer NOT NULL,
    "Status" public.verification_status DEFAULT 'pending'::public.verification_status NOT NULL
);
ALTER TABLE public."VerificationStatusEvent" ALTER COLUMN "EventId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VerificationStatusEvent_EventId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);
CREATE TABLE public.ir_model_fields (
    id integer NOT NULL,
    relation_field_id integer,
    model_id integer NOT NULL,
    related_field_id integer,
    size integer,
    create_uid integer,
    write_uid integer,
    name character varying NOT NULL,
    complete_name character varying,
    model character varying NOT NULL,
    relation character varying,
    relation_field character varying,
    ttype character varying NOT NULL,
    related character varying,
    state character varying NOT NULL,
    on_delete character varying,
    domain character varying,
    relation_table character varying,
    column1 character varying,
    column2 character varying,
    depends character varying,
    field_description jsonb NOT NULL,
    help jsonb,
    compute text,
    copied boolean,
    required boolean,
    readonly boolean,
    index boolean,
    translate boolean,
    group_expand boolean,
    selectable boolean,
    store boolean,
    create_date timestamp without time zone,
    write_date timestamp without time zone
);
CREATE SEQUENCE public.ir_model_fields_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.ir_model_fields_id_seq OWNED BY public.ir_model_fields.id;
ALTER TABLE ONLY public.ir_model_fields ALTER COLUMN id SET DEFAULT nextval('public.ir_model_fields_id_seq'::regclass);
ALTER TABLE ONLY public."InterestDoctor"
    ADD CONSTRAINT "InterestDoctor_pkey" PRIMARY KEY ("DoctorId", "InterestId");
ALTER TABLE ONLY public."IntersPatient"
    ADD CONSTRAINT "IntersPatient_pkey" PRIMARY KEY ("InterestId", "PatientId");
ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "PK_Answers" PRIMARY KEY ("AnswerId");
ALTER TABLE ONLY public."Articles"
    ADD CONSTRAINT "PK_Articles" PRIMARY KEY ("ArticleId");
ALTER TABLE ONLY public."Bookmarks"
    ADD CONSTRAINT "PK_Bookmarks" PRIMARY KEY ("BookmarkId");
ALTER TABLE ONLY public."CancerStages"
    ADD CONSTRAINT "PK_CancerStages" PRIMARY KEY ("StageId");
ALTER TABLE ONLY public."CancerTypes"
    ADD CONSTRAINT "PK_CancerTypes" PRIMARY KEY ("CancerId");
ALTER TABLE ONLY public."Contents"
    ADD CONSTRAINT "PK_Contents" PRIMARY KEY ("ContentId");
ALTER TABLE ONLY public."Countries"
    ADD CONSTRAINT "PK_Countries" PRIMARY KEY ("CountryId");
ALTER TABLE ONLY public."CountryStates"
    ADD CONSTRAINT "PK_CountryStates" PRIMARY KEY ("CountryStateId");
ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "PK_Doctors" PRIMARY KEY ("UserId");
ALTER TABLE ONLY public."InterestUser"
    ADD CONSTRAINT "PK_InterestUser" PRIMARY KEY ("InterestsInterestId", "UsersUserId");
ALTER TABLE ONLY public."Interests"
    ADD CONSTRAINT "PK_Interests" PRIMARY KEY ("InterestId");
ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("UserId");
ALTER TABLE ONLY public."Photos"
    ADD CONSTRAINT "PK_Photos" PRIMARY KEY ("PhotoId");
ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "PK_Questions" PRIMARY KEY ("QuestionId");
ALTER TABLE ONLY public."ResourceLocalization"
    ADD CONSTRAINT "PK_ResourceLocalization" PRIMARY KEY ("TranslationId");
ALTER TABLE ONLY public."Universities"
    ADD CONSTRAINT "PK_Universities" PRIMARY KEY ("UniversityId");
ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");
ALTER TABLE ONLY public."VerificationStatusEvent"
    ADD CONSTRAINT "PK_VerificationStatusEvent" PRIMARY KEY ("EventId");
ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");
ALTER TABLE ONLY public.ir_model_fields
    ADD CONSTRAINT ir_model_fields_pkey PRIMARY KEY (id);
CREATE INDEX "IX_Answers_DoctorId" ON public."Answers" USING btree ("DoctorId");
CREATE INDEX "IX_Answers_QuestionId" ON public."Answers" USING btree ("QuestionId");
CREATE INDEX "IX_Bookmarks_ArticleId" ON public."Bookmarks" USING btree ("ArticleId");
CREATE INDEX "IX_Bookmarks_UserId" ON public."Bookmarks" USING btree ("UserId");
CREATE INDEX "IX_Contents_AssignedTo" ON public."Contents" USING btree ("AssignedTo");
CREATE INDEX "IX_Contents_AuthorUserId" ON public."Contents" USING btree ("AuthorUserId");
CREATE INDEX "IX_Contents_ParentContentId" ON public."Contents" USING btree ("ParentContentId");
CREATE INDEX "IX_Contents_Tags" ON public."Contents" USING btree ("Tags");
CREATE INDEX "IX_Contents_Type" ON public."Contents" USING btree ("Type");
CREATE INDEX "IX_CountryStates_CountryId" ON public."CountryStates" USING btree ("CountryId");
CREATE INDEX "IX_InterestUser_UsersUserId" ON public."InterestUser" USING btree ("UsersUserId");
CREATE INDEX "IX_Patients_CancerStageId" ON public."Patients" USING btree ("CancerStageId");
CREATE INDEX "IX_Patients_CancerTypeId" ON public."Patients" USING btree ("CancerTypeId");
CREATE INDEX "IX_Questions_PatientUserId" ON public."Questions" USING btree ("PatientUserId");
CREATE INDEX "IX_Questions_UserId" ON public."Questions" USING btree ("UserId");
CREATE INDEX "IX_ResourceLocalization_CancerStageStageId" ON public."ResourceLocalization" USING btree ("CancerStageStageId");
CREATE INDEX "IX_ResourceLocalization_CancerTypeCancerId" ON public."ResourceLocalization" USING btree ("CancerTypeCancerId");
CREATE INDEX "IX_ResourceLocalization_InterestId" ON public."ResourceLocalization" USING btree ("InterestId");
CREATE INDEX "IX_Universities_CountryCode" ON public."Universities" USING btree ("CountryCode");
CREATE INDEX "IX_Universities_CountryCode_StateCode" ON public."Universities" USING btree ("CountryCode", "StateCode");
CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");
CREATE UNIQUE INDEX "IX_Users_MobileNumber" ON public."Users" USING btree ("MobileNumber");
CREATE INDEX "IX_VerificationStatusEvent_TargetDoctorUserId" ON public."VerificationStatusEvent" USING btree ("TargetDoctorUserId");
CREATE INDEX "IX_VerificationStatusEvent_UserId" ON public."VerificationStatusEvent" USING btree ("UserId");
CREATE INDEX "IX_VerificationStatusEvent_VerifierUserId" ON public."VerificationStatusEvent" USING btree ("VerifierUserId");
ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "FK_Answers_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES public."Questions"("QuestionId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Bookmarks"
    ADD CONSTRAINT "FK_Bookmarks_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("ArticleId");
ALTER TABLE ONLY public."Bookmarks"
    ADD CONSTRAINT "FK_Bookmarks_Doctors_UserId" FOREIGN KEY ("UserId") REFERENCES public."Doctors"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Bookmarks"
    ADD CONSTRAINT "FK_Bookmarks_Patients_UserId" FOREIGN KEY ("UserId") REFERENCES public."Patients"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Contents"
    ADD CONSTRAINT "FK_Contents_Contents_ParentContentId" FOREIGN KEY ("ParentContentId") REFERENCES public."Contents"("ContentId");
ALTER TABLE ONLY public."Contents"
    ADD CONSTRAINT "FK_Contents_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."CountryStates"
    ADD CONSTRAINT "FK_CountryStates_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("CountryId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "FK_Doctors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."InterestUser"
    ADD CONSTRAINT "FK_InterestUser_Users_UsersUserId" FOREIGN KEY ("UsersUserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_CancerStages_CancerStageId" FOREIGN KEY ("CancerStageId") REFERENCES public."CancerStages"("StageId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_CancerTypes_CancerTypeId" FOREIGN KEY ("CancerTypeId") REFERENCES public."CancerTypes"("CancerId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "FK_Questions_Patients_PatientUserId" FOREIGN KEY ("PatientUserId") REFERENCES public."Patients"("UserId");
ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "FK_Questions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."ResourceLocalization"
    ADD CONSTRAINT "FK_ResourceLocalization_CancerStages_CancerStageStageId" FOREIGN KEY ("CancerStageStageId") REFERENCES public."CancerStages"("StageId");
ALTER TABLE ONLY public."ResourceLocalization"
    ADD CONSTRAINT "FK_ResourceLocalization_CancerTypes_CancerTypeCancerId" FOREIGN KEY ("CancerTypeCancerId") REFERENCES public."CancerTypes"("CancerId");
ALTER TABLE ONLY public."ResourceLocalization"
    ADD CONSTRAINT "FK_ResourceLocalization_Interests_InterestId" FOREIGN KEY ("InterestId") REFERENCES public."Interests"("InterestId");
ALTER TABLE ONLY public."VerificationStatusEvent"
    ADD CONSTRAINT "FK_VerificationStatusEvent_Doctors_TargetDoctorUserId" FOREIGN KEY ("TargetDoctorUserId") REFERENCES public."Doctors"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."VerificationStatusEvent"
    ADD CONSTRAINT "FK_VerificationStatusEvent_Doctors_UserId" FOREIGN KEY ("UserId") REFERENCES public."Doctors"("UserId");
ALTER TABLE ONLY public."VerificationStatusEvent"
    ADD CONSTRAINT "FK_VerificationStatusEvent_Users_VerifierUserId" FOREIGN KEY ("VerifierUserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."InterestDoctor"
    ADD CONSTRAINT "InterestDoctor_DoctorId_fkey2" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("UserId") ON DELETE CASCADE;
ALTER TABLE ONLY public."InterestDoctor"
    ADD CONSTRAINT "InterestDoctor_InterestId_fkey" FOREIGN KEY ("InterestId") REFERENCES public."Interests"("InterestId") ON DELETE CASCADE;
ALTER TABLE ONLY public."InterestUser"
    ADD CONSTRAINT "InterestUser_InterestsInterestId_fkey" FOREIGN KEY ("InterestsInterestId") REFERENCES public."Interests"("InterestId") ON DELETE CASCADE;
ALTER TABLE ONLY public."IntersPatient"
    ADD CONSTRAINT "IntersPatient_InterestId_fkey" FOREIGN KEY ("InterestId") REFERENCES public."Interests"("InterestId") ON DELETE CASCADE;
ALTER TABLE ONLY public."IntersPatient"
    ADD CONSTRAINT "IntersPatient_PatientId_fkey" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("UserId") ON DELETE CASCADE;
